In [1]:
import numpy as np
import pandas as pd

In [2]:
Data = {
    'feature1': [1, 2, np.nan, 4, 5, np.nan, np.nan],
    'feature2': [np.nan, 4, 6, 8, 3, 5, 3],
    'feature3': [3, 0, 1, 1, np.nan, 1, np.nan]
}

df = pd.DataFrame(Data)
df

,feature1,feature2,feature3
0,1.0,NaN,3.0
1,2.0,4.0,0.0
2,NaN,6.0,1.0
3,4.0,8.0,1.0
4,5.0,3.0,NaN
5,NaN,5.0,1.0
6,NaN,3.0,NaN


In [3]:
from sklearn.impute import KNNImputer
imputer = KNNImputer()
df_imputed = imputer.fit_transform(df)
df_imputed

array([[1.        , 5.2       , 3.        ],
       [2.        , 4.        , 0.        ],
       [3.        , 6.        , 1.        ],
       [4.        , 8.        , 1.        ],
       [5.        , 3.        , 1.2       ],
       [3.        , 5.        , 1.        ],
       [3.66666667, 3.        , 0.75      ]])

by using loop

In [4]:
for i in range(1, 6):
    df_imputed = KNNImputer(n_neighbors=i).fit_transform(df)
    print (f"neighbors = {i} \n  {df_imputed} \n")

neighbors = 1 
  [[1. 6. 3.]
 [2. 4. 0.]
 [4. 6. 1.]
 [4. 8. 1.]
 [5. 3. 1.]
 [2. 5. 1.]
 [5. 3. 0.]] 

neighbors = 2 
  [[1.  5.5 3. ]
 [2.  4.  0. ]
 [3.  6.  1. ]
 [4.  8.  1. ]
 [5.  3.  0.5]
 [1.5 5.  1. ]
 [3.5 3.  0.5]] 

neighbors = 3 
  [[1.         5.         3.        ]
 [2.         4.         0.        ]
 [2.33333333 6.         1.        ]
 [4.         8.         1.        ]
 [5.         3.         0.66666667]
 [2.66666667 5.         1.        ]
 [3.66666667 3.         0.66666667]] 

neighbors = 4 
  [[1.         5.75       3.        ]
 [2.         4.         0.        ]
 [3.         6.         1.        ]
 [4.         8.         1.        ]
 [5.         3.         0.75      ]
 [3.         5.         1.        ]
 [3.66666667 3.         0.75      ]] 

neighbors = 5 
  [[1.         5.2        3.        ]
 [2.         4.         0.        ]
 [3.         6.         1.        ]
 [4.         8.         1.        ]
 [5.         3.         1.2       ]
 [3.         5.         1.    